import "./globals.css";

export const metadata = {
  title: "CineRental",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico",
  },
};

export default function RootLayout({ children }) {
  return <html lang="en">{children}</html>;
}
